[package]
name = "tracing-chrome"
version = "0.1.0"
authors = ["Thoren Paulson <thoren.paulson@gmail.com>"]
edition = "2018"

[dependencies]
json = "0.12.4"
tracing = "0.1.19"
tracing-subscriber = "0.2.11"
